config/routes.rb
Rails.application.routes.draw do

  get 'donations/index'
  root  "donations#index"
  resources :donations, only: [:index, :new, :create]

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :user

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base

  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
  end

app/models/user.rb
class User < ApplicationRecord
  has_one :address
  has_one :donation
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  def index
  end
  def new
    @donation = UserDonation.new   #「UserDonation」に編集
  end
 
  def create
    @donation = UserDonation.new(donation_params)   #「UserDonation」に編集
    binding.pry
    if @donation.valid?
      @donation.save  # バリデーションをクリアした時
      return redirect_to root_path
    else
      render "new"    # バリデーションに弾かれ時
    end
  end
 
   private
 
   def donation_params
    params.require(:user_donation).permit(:name, :name_reading, :nickname, :postal_code, :prefecture, :city, :house_number, :building_name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_error_messages.html.erb
<% if donation.errors.any? %>
 <div class="error-alert">
   <ul>
     <% donation.errors.full_messages.each do |message| %>
       <li class="error-message">
         <%= message %>
       </li>
     <% end %>
   </ul>
 </div>
<% end %>

app/views/donations/index.html.erb
<%= link_to '寄付する', new_donation_path %>

app/views/donations/new.html.erb
<%= form_with(model: @donation, url: donations_path, local: true) do |form| %>
  <%= render 'error_messages', donation: @donation %>
 <h1>ユーザー名を入力</h1>
 <div class="field">
   <%= form.label :name, "名前（全角）" %>
   <%= form.text_field :name %>
 </div>
 <div class="field">
   <%= form.label :name_reading, "フリカナ（全角カタカナ）" %>
   <%= form.text_field :name_reading %>
 </div>
 <div class="field">
   <%= form.label :nickname, "ニックネーム（半角英数）" %>
   <%= form.text_field :nickname %>
 </div>
 <h1>住所を入力</h1>
 <div class="field">
   <%= form.label :postal_code, "郵便番号（ハイフンを含む）" %>
   <%= form.text_field :postal_code %>
 </div>
  <div class="field">
   <%= form.label :prefecture, "都道府県" %>
   <%= form.collection_select :prefecture, Prefecture.all, :id, :name, {include_blank: "---"}, {required: true}  %>
 </div>

 <div class="field">
   <%= form.label :city, "市町村（任意）" %>
   <%= form.text_field :city %>
 </div>
 <div class="field">
   <%= form.label :house_number, "番地（任意）" %>
   <%= form.text_field :house_number %>
 </div>
 <div class="field">
   <%= form.label :building_name, "建物名（任意）" %>
   <%= form.text_field :building_name %>
 </div>

 <h1>寄付金</h1>
 <div class="field">
   <%= form.label :price, "いくら寄付しますか？（1〜1000000円、半角）" %>
   <%= form.text_field :price %>
   <%= "円" %>
 </div>
<div class="actions">
   <%= form.submit "寄付する" %>
 </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DonationApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>